### ISSUE TITLE
Get timings for Figure 15

### ISSUE THREAD

**Issue by weiya711** [weiya711/sam-artifact#10]

**Comment by weiya711** [comment]
1. Few points, no gold: 458 minute/8 hours
2. Few points, gold: XX
3. Full Run, no gold: XX
4. Full Run, gold: XX
5. Shortest point (which one XX): XX
6. Longest Running point (which one XX): XX
@Ritvik1sharma You need to fill in some of these ASAP

**Comment by Ritvik1sharma** [comment]
Pushed the numbers to README in the memory model file, bit as follows:
2. 19hrs 46min
3. 63 hrs 9 mins
4.  **Not done yet will run**
5. (5k nnz and 1024 dim): 23 mins 22 sec
6. (50k and 15720 dim):16hrs 59min 22sec

**Comment by weiya711** [comment]
For 2. I got 17 hours 24min. Will use @Ritvik1sharma's time

**Comment by weiya711** [comment]
4. 91 hours 54 min
