### ISSUE TITLE
Get disk usage 

### ISSUE THREAD

**Issue by weiya711** [weiya711/sam-artifact#5]
run all file creation commands and then see docker size.

**Comment by weiya711** [comment]
Need to run pre-tiling for Figure 15 disk usage: 
```
Call "./scripts/prepare_files_no_gold.sh extensor_${NNZ[$nnz]}_${DIMENSIONS[$dim]}.mtx"
For pre-tiling scripts with no gold files
Or ./scripts/prepare_files.sh extensor_${NNZ[$nnz]}_${DIMENSIONS[$dim]}.mtx
For pretiled matrices with gold
```

**Comment by Ritvik1sharma** [comment]
Max size: 1.8 Gb (will delete files after each tile)
11 Mb for extensor_mtx files

**Comment by weiya711** [comment]
After running DU max size is still around 4 GB. Putting 20 in artifact eval is good enough
