### ISSUE TITLE
Debug Table 1 CrdDrop, Residual, MatTransMul. SDDMM

### ISSUE THREAD

**Issue by weiya711** [weiya711/sam-artifact#8]
Show with empty reductions getting filtered out. SDDMM show non-optimized one

**Comment by weiya711** [comment]
1. Residual and Mattransmul fixed in `compiler_fix`
2. SDDMM should be changed to `2` in Table 1 (for unoptimized)
3. Still need to confirm all CrdDrops are correct for "filtered" empty reductions analytically

**Comment by weiya711** [comment]
Should be fixed once https://github.com/weiya711/sam/pull/75 is approved

**Comment by weiya711** [comment]
All CrdDrops have beenconfirmed analytically and the paper manuscript has been updated with final values

**Comment by mbstrange2** [comment]
Closed as per https://github.com/weiya711/sam/pull/75
